name: Run ikabot

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --user -e .
    - name: Just run ikabot
      run: |
        printf "\n\n" | python -m ikabot &> log.log || cat log.log
        grep "Wrong email or password" log.log && exit 0 || exit 1
