name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: get-pip
      run: Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py
    - name: Install PyInstaller
      run: python -m pip install PyInstaller
    - name: Install ikabot
      run: python -m pip install ikabot
    - name: Build
      run: python -m PyInstaller --onedir ikabot/command_line.py
    - name: Rename
      run: |
        mv dist/command_line dist/ikabot
        mv dist/ikabot/command_line.exe dist/ikabot/ikabot.exe
    - name: Zip
      run: Compress-Archive dist ikabot.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ikabot.zip
        asset_name: ikabot.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Ikabot binary"